# Generated by Django 4.2.7 on 2023-12-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('Task_assign_date', models.DateField(auto_now_add=True)),
                ('task_description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
