# Generated by Django 4.2.7 on 2023-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_addcategory_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='category.addcategory'),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='Task_assign_date',
            field=models.DateField(),
        ),
    ]
